# Convoluciones y convoluciones transpuestas

In [1]:
import torch
import torch.nn as nn

In [2]:
KERNEL = torch.tensor([1.0, 2.0, 3.0])
STRIDE = 2

## Convolución directa

In [3]:
# Entrada:
x = torch.tensor([4.0, 5.0, 6.0, 7.0, 8.0])

### Como producto matricial

In [4]:
A = torch.tensor([
    [1.0, 2.0, 3.0, 0.0, 0.0],
    [0.0, 0.0, 1.0, 2.0, 3.0]
])

y_matricial = A @ x

print(y_matricial)

tensor([32., 44.])


### Usando `Conv1d`

In [5]:
conv = nn.Conv1d(1, 1, kernel_size=len(KERNEL), stride=STRIDE, bias=False)
conv.weight.data = KERNEL.view(1, 1, -1)

y_torch = conv(x.view(1, 1, -1))

print(y_torch.flatten())

tensor([32., 44.], grad_fn=<ViewBackward0>)


## Convolución transpuesta

In [6]:
# Entrada:
x = torch.tensor([9.0, 10.0])

### Como producto matricial

In [7]:
y_matricial = A.T @ x

print(y_matricial)

tensor([ 9., 18., 37., 20., 30.])


### Usando `ConvTranspose1d`

In [8]:
transposed_conv = nn.ConvTranspose1d(1, 1, kernel_size=len(KERNEL), stride=STRIDE, bias=False)
transposed_conv.weight.data = KERNEL.view(1, 1, -1)

y_torch = transposed_conv(x.view(1, 1, -1))

print(y_torch.flatten())

tensor([ 9., 18., 37., 20., 30.], grad_fn=<ViewBackward0>)
